# Generated by Django 5.1.7 on 2025-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
