# Generated by Django 5.1.7 on 2025-05-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('china', 'Chinese'), ('local', 'Local')], max_length=20)),
                ('unique_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
    ]
