# Generated by Django 5.1.7 on 2025-05-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_counterpartystatus_counterparty_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterpartystatus',
            name='color',
            field=models.CharField(default='#999999', max_length=7),
        ),
    ]
