# Generated by Django 5.1.7 on 2025-05-21 08:43

import django.db.models.deletion
import supplier_orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0003_alter_counterparty_created_by_and_more'),
        ('products', '0006_remove_product_price_yuan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_shipping_address', models.TextField(blank=True, verbose_name='Адрес отгрузки по умолчанию')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет (hex)')),
            ],
            options={
                'verbose_name': 'Статус заказа поставщику',
                'verbose_name_plural': 'Статусы заказа поставщику',
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('planned_receipt_date', models.DateField(blank=True, null=True, verbose_name='План. дата приёмки')),
                ('shipping_address', models.TextField(blank=True, default=supplier_orders.models.get_default_shipping_address, verbose_name='Адрес отгрузки')),
                ('shipping_code', models.CharField(blank=True, max_length=100, verbose_name='Код точки отгрузки')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('china_exit_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода из Китая')),
                ('supplier_comment', models.TextField(blank=True, verbose_name='Комментарий для поставщика')),
                ('amount_cny', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма в юанях')),
                ('track_number', models.CharField(blank=True, max_length=200, verbose_name='Трек-номер')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата получения')),
                ('logistic_invoice_no', models.CharField(blank=True, max_length=200, verbose_name='Номер накладной логистов')),
                ('production_due_date', models.DateField(blank=True, null=True, verbose_name='Срок производства до')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('payment_details_qr', models.ImageField(blank=True, help_text='Подгружается из карточки поставщика', upload_to='qr_codes/', verbose_name='QR для оплаты')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='counterparties.counterparty', verbose_name='Покупатель')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='counterparties.counterparty', verbose_name='Поставщик')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_orders', to='supplier_orders.supplierorderstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ поставщику',
                'verbose_name_plural': 'Заказы поставщику',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changes', to=settings.AUTH_USER_MODEL)),
                ('supplier_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='supplier_orders.supplierorder')),
            ],
            options={
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица измерения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к позиции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplier_orders.supplierorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_order_items', to='products.product', verbose_name='Товар')),
            ],
        ),
    ]
