# Generated by Django 5.1.7 on 2025-05-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='supplier_order_attachments/', verbose_name='Attachment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='supplier_orders.supplierorder', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Attachment',
                'verbose_name_plural': 'Order Attachments',
            },
        ),
    ]
