# Generated by Django 5.1.7 on 2025-05-27 14:16

import customer_orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0003_alter_counterparty_created_by_and_more'),
        ('products', '0006_remove_product_price_yuan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color (hex)')),
            ],
            options={
                'verbose_name': 'Customer Order Status',
                'verbose_name_plural': 'Customer Order Statuses',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_shipping_address', models.TextField(blank=True, verbose_name='Default Shipping Address')),
            ],
            options={
                'verbose_name': 'Shipping Address Setting',
                'verbose_name_plural': 'Shipping Address Settings',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Order Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('planned_receipt_date', models.DateField(blank=True, null=True, verbose_name='Planned Receipt Date')),
                ('shipping_address', models.TextField(blank=True, default=customer_orders.models.get_default_shipping_address, verbose_name='Shipping Address')),
                ('shipping_code', models.CharField(blank=True, max_length=100, verbose_name='Shipping Point Code')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Shipment Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='counterparties.counterparty', verbose_name='Customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='customer_orders.customerorderstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Customer Order',
                'verbose_name_plural': 'Customer Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='customer_order_attachments/', verbose_name='Attachment File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='customer_orders.customerorder', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Customer Order Attachment',
                'verbose_name_plural': 'Customer Order Attachments',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changes', to=settings.AUTH_USER_MODEL)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='customer_orders.customerorder')),
            ],
            options={
                'verbose_name': 'Customer Order Change Log',
                'verbose_name_plural': 'Customer Order Change Logs',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unit of Measure')),
                ('comment', models.TextField(blank=True, verbose_name='Line Comment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer_orders.customerorder', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_items', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Customer Order Item',
                'verbose_name_plural': 'Customer Order Items',
            },
        ),
    ]
