# Generated by Django 5.1.7 on 2025-05-19 12:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_discount_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='discount_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Enter 0.10 for 10%', max_digits=5, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='margin_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.50'), help_text='Enter 0.10 for 10%', max_digits=5, verbose_name='Margin (%)'),
        ),
    ]
