# Generated by Django 5.1.7 on 2025-05-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_globalsettings_discount_pct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_yuan',
        ),
    ]
